Getting data from google via backend
Cource-startup/main_api pull request #2
Opened 2024-06-13 12:28 UTC by Panton1986

Added file "google_auth_controller"
Added route: {"rule": "/checking", "methods": ["POST"], "view_func": google_auth_controller.checking},

2024-06-15 02:07 UTC, denis-progman requested changes
Please fix and comment back all the  comments. We can discuss the details in the dev chat.

2024-06-15 02:07 UTC, denis-progman commented on app/controllers/google_auth_controller.py
> +    google_id = id_info.get("sub")
you don't need these vars, you can put it directly into the 'response' object below

2024-06-15 02:07 UTC, denis-progman commented on app/controllers/user_controller.py
> +        auth_code = data.get('serverAuthCode')
better to make 'serverAuthCode' and 'code' and 'input_string' and 'SECRET_CODE' class's constants

2024-07-09 12:29 UTC, Panton1986 commented on app/controllers/google_auth_controller.py
> +
Done

2024-07-09 12:29 UTC, Panton1986 commented on app/controllers/google_auth_controller.py
> +def checking():
Done

2024-07-09 12:29 UTC, Panton1986 commented on app/controllers/user_controller.py
> +    def checking():
Done

2024-07-09 12:29 UTC, Panton1986 commented on app/controllers/user_controller.py
> +        session['key'] = hashlib.sha256(special_code.encode()).hexdigest()
Done

2024-07-09 12:36 UTC, Panton1986 commented on app/controllers/user_controller.py
> +        auth_code = data.get('serverAuthCode')
Done

2024-07-18 02:16 UTC, Panton1986 commented on app/controllers/user_controller.py
> +        CLIENT_SECRET_FILE = os.path.join(pathlib.Path(__file__).parent, "client_secret.json")
Done

2024-07-18 02:16 UTC, Panton1986 commented on app/controllers/google_auth_controller.py
> +    pathlib.Path(__file__).parent, "client_secret.json")
Done

2024-07-18 02:16 UTC, Panton1986 commented on app/controllers/google_auth_controller.py
> +os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"
moved to the config

2024-07-18 02:17 UTC, Panton1986 commented on app/controllers/google_auth_controller.py
> +    google_id = id_info.get("sub")
object creates in return directly

2024-07-19 03:25 UTC, denis-progman reviewed
Plese comment all the review comments

2024-07-19 03:25 UTC, denis-progman commented on app/.venv/bin/Activate.ps1
please remove the .venv folder, this is trash. Add it to git ignore when run git rm -r app/.venv and commit it (removes the folder from your computer as well, but I believe you don't need it, we use docker...)
then make sure that .venv is disappeared and do 'push'.

2024-07-19 03:25 UTC, denis-progman commented on app/router.py
>  from controllers import GamerController
???

2024-07-19 03:33 UTC, denis-progman reviewed
don't forget removing .venv

2024-07-19 03:33 UTC, denis-progman commented on app/controllers/google_auth_controller.py
> +    scopes=["https://www.googleapis.com/auth/userinfo.profile",
???

2024-07-19 03:33 UTC, denis-progman commented on app/controllers/google_auth_controller.py
> +def checking():
Are you sure you have created class Service for Google auth?  and there is no class ion the controller part as I see.. Check it out please.

2024-07-19 03:33 UTC, denis-progman commented on app/controllers/user_controller.py
> +            ['https://www.googleapis.com/auth/drive.appdata', 'profile', 'email'],
???

2024-07-21 11:34 UTC, Panton1986 commented on app/controllers/google_auth_controller.py
> +def checking():
I've checked it out. Classes have created for every service and controller

2024-07-21 12:23 UTC, Panton1986 commented on app/router.py
>  from controllers import GamerController
All unused file deleted

2024-07-21 12:23 UTC, Panton1986 commented on app/.venv/bin/Activate.ps1
Done

2024-07-21 12:29 UTC, Panton1986 commented on app/controllers/google_auth_controller.py
> +    scopes=["https://www.googleapis.com/auth/userinfo.profile",
Gentle information moved to .env and config files. Strings moved to class' constants

2024-07-23 01:06 UTC, denis-progman approved these changes

2024-07-23 01:06 UTC, denis-progman commented
cool, thanks!

2024-07-23 01:09 UTC, merged