featuer: Session added
Cource-startup/main_api pull request #5
Opened 2024-08-23 00:25 UTC by Panton1986

Created session for user.
Could you check one issue with hashed code?
Timur and me use the same method to create a code, however, there are two different codes.

- Timur's code is:
2024-08-23 09:45:46 VmvhK6tI7wH64+eFwoSlUm1DlNJMYfIw3faFj2ffSEE=

- My code is:
2024-08-23 09:45:46 b'Vk\xe1+\xabH\xef\x01\xfa\xe3\xe7\x85\xc2\x84\xa5RmC\x94\xd2La\xf20\xdd\xf6\x85\x8fg\xdfHA'

2024-08-23 02:54 UTC, denis-progman requested changes
needs some changes, lets discuss the details you need personally. And about the codes you've mentioned as well.

2024-08-23 02:54 UTC, denis-progman commented on app/app.py
>  app_instance.config["SESSION_TYPE"] = "filesystem"
should come from the app config

2024-08-23 02:54 UTC, denis-progman commented on app/controllers/session_controller.py
> +    def check_session(id):
works mach more like "get_session" by the logic

2024-09-25 01:05 UTC, Panton1986 commented on app/services/session_service.py
> +        session["key"] = UserService.get_user_by_id(id)['user']['user_name']
I set the session's key as user's name just for test. I will change it in future, but I need something for now.

2024-09-25 01:08 UTC, Panton1986 commented on app/services/session_service.py
> +           return "session is expired"
It's not clear for me. We try to avoid any logic on the controller level. So I will keep it as it is for now. Let discuss it.

2024-09-27 01:25 UTC, denis-progman commented on app/services/session_service.py
> +        session["key"] = UserService.get_user_by_id(id)['user']['user_name']
remaining...

2024-09-27 01:34 UTC, denis-progman commented on app/services/session_service.py
> +           return "session is expired"
remaining...

2024-09-27 01:40 UTC, Panton1986 commented
Done

2024-09-27 02:13 UTC, denis-progman reviewed
check

2024-09-27 02:35 UTC, closed without merging

2024-09-27 02:35 UTC, denis-progman commented
need some more work